# Flags:
# "a" - the item is not available before the infection begins
# "b" - the item is not available after the infection begins
# "c" - the item is not available to the first zombie
# "d" - the item is not available to the last zombie
# "e" - the item is not available to the last human
# "f" - the item is not available in the "Infection" round
# "g" - the item is not available in the "Multi-Infection" round
# "l" - multi-language name ("Menu Name" -> Keyword for the language file)
# "m" - RoundLimit = how many times the item is available per round

# a b c d e f g h i j k l m n o p q r s t u v w x y z

# Keywords
# Name = Menu Name
# ExtraName = Name in Extra / Original "weapon_*" name
# Cost = Price
# Souls = Price in souls
# Flags = Flags
# RoundLimit = How many times the item is available per round (each player has their own limit)
# Players = How many players must be on the server for the item to be available
# MaxUsed = Maximum number of times an item can be purchased per round (total limit)

# String format
"Name" "ExtraName" "Cost" "Souls" "Flags" "RoundLimit" "Players" "MaxUsed"

# Example of adding an item
# "Desert Deagle" "weapon_deagle" "10" "" "ac" "5" "10" "50"

# Example of blocking weapon pickup by level
# "WeaponKey" "Required level"

# Do not edit the text in "[]"
# Follow the format when adding items

[PISTOLS]
{
}

[SHOTGUNS]
{
"SPAS-12" "spas12m" "45" "" "" "" "" ""
}

[AUTOMATES]
{
"K1A(SE)" "k1ase" "35" "" "" "" "" ""
"MP7 Unicorn" "mp7h" "45" "" "" "" "" ""
}

[RIFLES]
{
"AK74-U" "ak74u" "60" "" "" "" "" ""
"M14 Ebr." "m14" "60" "1" "" "" "" ""
"Bendita" "bendita" "100" "1" "" "" "" ""
}

[MACHINEGUNS]
{
"QBB95-EX" "qbb95ex" "150" "1" "" "" "" ""
"M60E4" "m60e4" "175" "2" "" "" "" ""
}

[ITEMS]
{
"Freeze Nade" "weapon_flashbang" "100" "" "m" "2" "" ""
"Flare Nade" "weapon_smokegrenade" "30" "" "m" "4" "" ""
"NVG" "Nightvision" "100" "" "m" "1" "" ""
"Medkit +30" "Medkit" "35" "" "m" "2" "" ""
"Deadly bullet" "Deadly bullet" "" "5" "m" "2" "8" ""
}

[ZITEMS]
{
"Virus Nade" "Infection Bomb" "360" "3" "m" "1" "" "1"
"Chain Infection" "Chainy infection" "150" "1" "m" "1" "" ""
"Instant Infection On Hit" "Instant infect" "150" "0" "m" "1" "" ""
}

[KNIFE]
{
"Standart Knife" "standartknife" "" "" "" "" "" ""
"Strong Knife" "strongknife" "80" "" "" "" "" ""
}

[VIP]
{
"Frag Nade" "weapon_hegrenade" "100" "" "m" "2" "" ""
}

[WEAPONKEYS]
{
}